
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'About': typeof import("../components/About.vue")['default']
    'Blog': typeof import("../components/Blog.vue")['default']
    'Clients': typeof import("../components/Clients.vue")['default']
    'Contact': typeof import("../components/Contact.vue")['default']
    'Error': typeof import("../components/Error.vue")['default']
    'Footer2': typeof import("../components/Footer2.vue")['default']
    'FooterPrimary': typeof import("../components/FooterPrimary.vue")['default']
    'FooterSecondary': typeof import("../components/FooterSecondary.vue")['default']
    'FooterTertiary': typeof import("../components/FooterTertiary.vue")['default']
    'HeroMain': typeof import("../components/HeroMain.vue")['default']
    'ImageScale': typeof import("../components/ImageScale.vue")['default']
    'Marquee': typeof import("../components/Marquee.vue")['default']
    'Navbar': typeof import("../components/Navbar.vue")['default']
    'Portfolio': typeof import("../components/Portfolio.vue")['default']
    'Services': typeof import("../components/Services.vue")['default']
    'Skills': typeof import("../components/Skills.vue")['default']
    'Testimonials': typeof import("../components/Testimonials.vue")['default']
    'CommonFooter': typeof import("../components/common/Footer.vue")['default']
    'CommonLines': typeof import("../components/common/Lines.vue")['default']
    'CommonProgressScroll': typeof import("../components/common/ProgressScroll.vue")['default']
    'CommonCusor': typeof import("../components/common/cusor.vue")['default']
    'CommonLoader': typeof import("../components/common/loader.vue")['default']
    'DarkAbout': typeof import("../components/dark/About.vue")['default']
    'DarkAboutBlog': typeof import("../components/dark/about/Blog.vue")['default']
    'DarkAboutFooter': typeof import("../components/dark/about/Footer.vue")['default']
    'DarkAboutHeader': typeof import("../components/dark/about/Header.vue")['default']
    'DarkAboutIntro': typeof import("../components/dark/about/Intro.vue")['default']
    'DarkAboutIntro2': typeof import("../components/dark/about/Intro2.vue")['default']
    'DarkAboutMarquee': typeof import("../components/dark/about/Marquee.vue")['default']
    'DarkAboutTeam': typeof import("../components/dark/about/Team.vue")['default']
    'DarkAboutTestimonials': typeof import("../components/dark/about/Testimonials.vue")['default']
    'DarkBlogClassicFooter': typeof import("../components/dark/blog-classic/Footer.vue")['default']
    'DarkBlogDetailsBlog': typeof import("../components/dark/blog-details/Blog.vue")['default']
    'DarkBlogDetailsFooter': typeof import("../components/dark/blog-details/Footer.vue")['default']
    'DarkBlogDetailsRecent': typeof import("../components/dark/blog-details/Recent.vue")['default']
    'DarkBlogDetailsSlider': typeof import("../components/dark/blog-details/Slider.vue")['default']
    'DarkBlogListBlogs': typeof import("../components/dark/blog-list/Blogs.vue")['default']
    'DarkBlogListHeader': typeof import("../components/dark/blog-list/Header.vue")['default']
    'DarkContact': typeof import("../components/dark/contact/Contact.vue")['default']
    'DarkContactHeader': typeof import("../components/dark/contact/Header.vue")['default']
    'DarkCreativeAgencyFooter': typeof import("../components/dark/creative-agency/Footer.vue")['default']
    'DarkCreativeAgencyNavbar': typeof import("../components/dark/creative-agency/Navbar.vue")['default']
    'DarkFaqBlog': typeof import("../components/dark/faq/Blog.vue")['default']
    'DarkFaqFAQS': typeof import("../components/dark/faq/FAQS.vue")['default']
    'DarkFaqHeader': typeof import("../components/dark/faq/Header.vue")['default']
    'DarkFaqTestimonials': typeof import("../components/dark/faq/Testimonials.vue")['default']
    'DarkHomeMainBlog': typeof import("../components/dark/home-main/Blog.vue")['default']
    'DarkHomeMainClients': typeof import("../components/dark/home-main/Clients.vue")['default']
    'DarkHomeMainFooter': typeof import("../components/dark/home-main/Footer.vue")['default']
    'DarkHomeMainHeader': typeof import("../components/dark/home-main/Header.vue")['default']
    'DarkHomeMainIntro': typeof import("../components/dark/home-main/Intro.vue")['default']
    'DarkHomeMainMarquee': typeof import("../components/dark/home-main/Marquee.vue")['default']
    'DarkHomeMainPortfolio': typeof import("../components/dark/home-main/Portfolio.vue")['default']
    'DarkHomeMainServices': typeof import("../components/dark/home-main/Services.vue")['default']
    'DarkHomeMainServices2': typeof import("../components/dark/home-main/Services2.vue")['default']
    'DarkHomeMainTeam': typeof import("../components/dark/home-main/Team.vue")['default']
    'DarkHomeMainTestimonials': typeof import("../components/dark/home-main/Testimonials.vue")['default']
    'DarkInteractiveFullInteractive': typeof import("../components/dark/interactive-full/Interactive.vue")['default']
    'DarkPortfolioHeader': typeof import("../components/dark/portfolio/Header.vue")['default']
    'DarkPortfolioNavbar': typeof import("../components/dark/portfolio/Navbar.vue")['default']
    'DarkPortfolio': typeof import("../components/dark/portfolio/Portfolio.vue")['default']
    'DarkProjectChallenge': typeof import("../components/dark/project/Challenge.vue")['default']
    'DarkProjectHeader': typeof import("../components/dark/project/Header.vue")['default']
    'DarkProjectNext': typeof import("../components/dark/project/Next.vue")['default']
    'DarkProjectSolution': typeof import("../components/dark/project/Solution.vue")['default']
    'DarkProjectWorks': typeof import("../components/dark/project/Works.vue")['default']
    'DarkProjectWorks2': typeof import("../components/dark/project/Works2.vue")['default']
    'DarkServicesDetailsFAQS': typeof import("../components/dark/services-details/FAQS.vue")['default']
    'DarkServicesDetailsHeader': typeof import("../components/dark/services-details/Header.vue")['default']
    'DarkServicesDetailsProcess': typeof import("../components/dark/services-details/Process.vue")['default']
    'DarkServicesDetailsServices': typeof import("../components/dark/services-details/Services.vue")['default']
    'DarkServicesBlog': typeof import("../components/dark/services/Blog.vue")['default']
    'DarkServicesHeader': typeof import("../components/dark/services/Header.vue")['default']
    'DarkServicesMarquee': typeof import("../components/dark/services/Marquee.vue")['default']
    'DarkServicesPrice': typeof import("../components/dark/services/Price.vue")['default']
    'DarkServicesProcess': typeof import("../components/dark/services/Process.vue")['default']
    'DarkServices': typeof import("../components/dark/services/Services.vue")['default']
    'DarkServicesServices2': typeof import("../components/dark/services/Services2.vue")['default']
    'DarkServices2Brands': typeof import("../components/dark/services2/Brands.vue")['default']
    'DarkShowcaseFullscreenHeader': typeof import("../components/dark/showcase-fullscreen/Header.vue")['default']
    'DarkTeamHeader': typeof import("../components/dark/team/Header.vue")['default']
    'DarkTeam': typeof import("../components/dark/team/Team.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAbout': typeof import("../components/About.vue")['default']
    'LazyBlog': typeof import("../components/Blog.vue")['default']
    'LazyClients': typeof import("../components/Clients.vue")['default']
    'LazyContact': typeof import("../components/Contact.vue")['default']
    'LazyError': typeof import("../components/Error.vue")['default']
    'LazyFooter2': typeof import("../components/Footer2.vue")['default']
    'LazyFooterPrimary': typeof import("../components/FooterPrimary.vue")['default']
    'LazyFooterSecondary': typeof import("../components/FooterSecondary.vue")['default']
    'LazyFooterTertiary': typeof import("../components/FooterTertiary.vue")['default']
    'LazyHeroMain': typeof import("../components/HeroMain.vue")['default']
    'LazyImageScale': typeof import("../components/ImageScale.vue")['default']
    'LazyMarquee': typeof import("../components/Marquee.vue")['default']
    'LazyNavbar': typeof import("../components/Navbar.vue")['default']
    'LazyPortfolio': typeof import("../components/Portfolio.vue")['default']
    'LazyServices': typeof import("../components/Services.vue")['default']
    'LazySkills': typeof import("../components/Skills.vue")['default']
    'LazyTestimonials': typeof import("../components/Testimonials.vue")['default']
    'LazyCommonFooter': typeof import("../components/common/Footer.vue")['default']
    'LazyCommonLines': typeof import("../components/common/Lines.vue")['default']
    'LazyCommonProgressScroll': typeof import("../components/common/ProgressScroll.vue")['default']
    'LazyCommonCusor': typeof import("../components/common/cusor.vue")['default']
    'LazyCommonLoader': typeof import("../components/common/loader.vue")['default']
    'LazyDarkAbout': typeof import("../components/dark/About.vue")['default']
    'LazyDarkAboutBlog': typeof import("../components/dark/about/Blog.vue")['default']
    'LazyDarkAboutFooter': typeof import("../components/dark/about/Footer.vue")['default']
    'LazyDarkAboutHeader': typeof import("../components/dark/about/Header.vue")['default']
    'LazyDarkAboutIntro': typeof import("../components/dark/about/Intro.vue")['default']
    'LazyDarkAboutIntro2': typeof import("../components/dark/about/Intro2.vue")['default']
    'LazyDarkAboutMarquee': typeof import("../components/dark/about/Marquee.vue")['default']
    'LazyDarkAboutTeam': typeof import("../components/dark/about/Team.vue")['default']
    'LazyDarkAboutTestimonials': typeof import("../components/dark/about/Testimonials.vue")['default']
    'LazyDarkBlogClassicFooter': typeof import("../components/dark/blog-classic/Footer.vue")['default']
    'LazyDarkBlogDetailsBlog': typeof import("../components/dark/blog-details/Blog.vue")['default']
    'LazyDarkBlogDetailsFooter': typeof import("../components/dark/blog-details/Footer.vue")['default']
    'LazyDarkBlogDetailsRecent': typeof import("../components/dark/blog-details/Recent.vue")['default']
    'LazyDarkBlogDetailsSlider': typeof import("../components/dark/blog-details/Slider.vue")['default']
    'LazyDarkBlogListBlogs': typeof import("../components/dark/blog-list/Blogs.vue")['default']
    'LazyDarkBlogListHeader': typeof import("../components/dark/blog-list/Header.vue")['default']
    'LazyDarkContact': typeof import("../components/dark/contact/Contact.vue")['default']
    'LazyDarkContactHeader': typeof import("../components/dark/contact/Header.vue")['default']
    'LazyDarkCreativeAgencyFooter': typeof import("../components/dark/creative-agency/Footer.vue")['default']
    'LazyDarkCreativeAgencyNavbar': typeof import("../components/dark/creative-agency/Navbar.vue")['default']
    'LazyDarkFaqBlog': typeof import("../components/dark/faq/Blog.vue")['default']
    'LazyDarkFaqFAQS': typeof import("../components/dark/faq/FAQS.vue")['default']
    'LazyDarkFaqHeader': typeof import("../components/dark/faq/Header.vue")['default']
    'LazyDarkFaqTestimonials': typeof import("../components/dark/faq/Testimonials.vue")['default']
    'LazyDarkHomeMainBlog': typeof import("../components/dark/home-main/Blog.vue")['default']
    'LazyDarkHomeMainClients': typeof import("../components/dark/home-main/Clients.vue")['default']
    'LazyDarkHomeMainFooter': typeof import("../components/dark/home-main/Footer.vue")['default']
    'LazyDarkHomeMainHeader': typeof import("../components/dark/home-main/Header.vue")['default']
    'LazyDarkHomeMainIntro': typeof import("../components/dark/home-main/Intro.vue")['default']
    'LazyDarkHomeMainMarquee': typeof import("../components/dark/home-main/Marquee.vue")['default']
    'LazyDarkHomeMainPortfolio': typeof import("../components/dark/home-main/Portfolio.vue")['default']
    'LazyDarkHomeMainServices': typeof import("../components/dark/home-main/Services.vue")['default']
    'LazyDarkHomeMainServices2': typeof import("../components/dark/home-main/Services2.vue")['default']
    'LazyDarkHomeMainTeam': typeof import("../components/dark/home-main/Team.vue")['default']
    'LazyDarkHomeMainTestimonials': typeof import("../components/dark/home-main/Testimonials.vue")['default']
    'LazyDarkInteractiveFullInteractive': typeof import("../components/dark/interactive-full/Interactive.vue")['default']
    'LazyDarkPortfolioHeader': typeof import("../components/dark/portfolio/Header.vue")['default']
    'LazyDarkPortfolioNavbar': typeof import("../components/dark/portfolio/Navbar.vue")['default']
    'LazyDarkPortfolio': typeof import("../components/dark/portfolio/Portfolio.vue")['default']
    'LazyDarkProjectChallenge': typeof import("../components/dark/project/Challenge.vue")['default']
    'LazyDarkProjectHeader': typeof import("../components/dark/project/Header.vue")['default']
    'LazyDarkProjectNext': typeof import("../components/dark/project/Next.vue")['default']
    'LazyDarkProjectSolution': typeof import("../components/dark/project/Solution.vue")['default']
    'LazyDarkProjectWorks': typeof import("../components/dark/project/Works.vue")['default']
    'LazyDarkProjectWorks2': typeof import("../components/dark/project/Works2.vue")['default']
    'LazyDarkServicesDetailsFAQS': typeof import("../components/dark/services-details/FAQS.vue")['default']
    'LazyDarkServicesDetailsHeader': typeof import("../components/dark/services-details/Header.vue")['default']
    'LazyDarkServicesDetailsProcess': typeof import("../components/dark/services-details/Process.vue")['default']
    'LazyDarkServicesDetailsServices': typeof import("../components/dark/services-details/Services.vue")['default']
    'LazyDarkServicesBlog': typeof import("../components/dark/services/Blog.vue")['default']
    'LazyDarkServicesHeader': typeof import("../components/dark/services/Header.vue")['default']
    'LazyDarkServicesMarquee': typeof import("../components/dark/services/Marquee.vue")['default']
    'LazyDarkServicesPrice': typeof import("../components/dark/services/Price.vue")['default']
    'LazyDarkServicesProcess': typeof import("../components/dark/services/Process.vue")['default']
    'LazyDarkServices': typeof import("../components/dark/services/Services.vue")['default']
    'LazyDarkServicesServices2': typeof import("../components/dark/services/Services2.vue")['default']
    'LazyDarkServices2Brands': typeof import("../components/dark/services2/Brands.vue")['default']
    'LazyDarkShowcaseFullscreenHeader': typeof import("../components/dark/showcase-fullscreen/Header.vue")['default']
    'LazyDarkTeamHeader': typeof import("../components/dark/team/Header.vue")['default']
    'LazyDarkTeam': typeof import("../components/dark/team/Team.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const About: typeof import("../components/About.vue")['default']
export const Blog: typeof import("../components/Blog.vue")['default']
export const Clients: typeof import("../components/Clients.vue")['default']
export const Contact: typeof import("../components/Contact.vue")['default']
export const Error: typeof import("../components/Error.vue")['default']
export const Footer2: typeof import("../components/Footer2.vue")['default']
export const FooterPrimary: typeof import("../components/FooterPrimary.vue")['default']
export const FooterSecondary: typeof import("../components/FooterSecondary.vue")['default']
export const FooterTertiary: typeof import("../components/FooterTertiary.vue")['default']
export const HeroMain: typeof import("../components/HeroMain.vue")['default']
export const ImageScale: typeof import("../components/ImageScale.vue")['default']
export const Marquee: typeof import("../components/Marquee.vue")['default']
export const Navbar: typeof import("../components/Navbar.vue")['default']
export const Portfolio: typeof import("../components/Portfolio.vue")['default']
export const Services: typeof import("../components/Services.vue")['default']
export const Skills: typeof import("../components/Skills.vue")['default']
export const Testimonials: typeof import("../components/Testimonials.vue")['default']
export const CommonFooter: typeof import("../components/common/Footer.vue")['default']
export const CommonLines: typeof import("../components/common/Lines.vue")['default']
export const CommonProgressScroll: typeof import("../components/common/ProgressScroll.vue")['default']
export const CommonCusor: typeof import("../components/common/cusor.vue")['default']
export const CommonLoader: typeof import("../components/common/loader.vue")['default']
export const DarkAbout: typeof import("../components/dark/About.vue")['default']
export const DarkAboutBlog: typeof import("../components/dark/about/Blog.vue")['default']
export const DarkAboutFooter: typeof import("../components/dark/about/Footer.vue")['default']
export const DarkAboutHeader: typeof import("../components/dark/about/Header.vue")['default']
export const DarkAboutIntro: typeof import("../components/dark/about/Intro.vue")['default']
export const DarkAboutIntro2: typeof import("../components/dark/about/Intro2.vue")['default']
export const DarkAboutMarquee: typeof import("../components/dark/about/Marquee.vue")['default']
export const DarkAboutTeam: typeof import("../components/dark/about/Team.vue")['default']
export const DarkAboutTestimonials: typeof import("../components/dark/about/Testimonials.vue")['default']
export const DarkBlogClassicFooter: typeof import("../components/dark/blog-classic/Footer.vue")['default']
export const DarkBlogDetailsBlog: typeof import("../components/dark/blog-details/Blog.vue")['default']
export const DarkBlogDetailsFooter: typeof import("../components/dark/blog-details/Footer.vue")['default']
export const DarkBlogDetailsRecent: typeof import("../components/dark/blog-details/Recent.vue")['default']
export const DarkBlogDetailsSlider: typeof import("../components/dark/blog-details/Slider.vue")['default']
export const DarkBlogListBlogs: typeof import("../components/dark/blog-list/Blogs.vue")['default']
export const DarkBlogListHeader: typeof import("../components/dark/blog-list/Header.vue")['default']
export const DarkContact: typeof import("../components/dark/contact/Contact.vue")['default']
export const DarkContactHeader: typeof import("../components/dark/contact/Header.vue")['default']
export const DarkCreativeAgencyFooter: typeof import("../components/dark/creative-agency/Footer.vue")['default']
export const DarkCreativeAgencyNavbar: typeof import("../components/dark/creative-agency/Navbar.vue")['default']
export const DarkFaqBlog: typeof import("../components/dark/faq/Blog.vue")['default']
export const DarkFaqFAQS: typeof import("../components/dark/faq/FAQS.vue")['default']
export const DarkFaqHeader: typeof import("../components/dark/faq/Header.vue")['default']
export const DarkFaqTestimonials: typeof import("../components/dark/faq/Testimonials.vue")['default']
export const DarkHomeMainBlog: typeof import("../components/dark/home-main/Blog.vue")['default']
export const DarkHomeMainClients: typeof import("../components/dark/home-main/Clients.vue")['default']
export const DarkHomeMainFooter: typeof import("../components/dark/home-main/Footer.vue")['default']
export const DarkHomeMainHeader: typeof import("../components/dark/home-main/Header.vue")['default']
export const DarkHomeMainIntro: typeof import("../components/dark/home-main/Intro.vue")['default']
export const DarkHomeMainMarquee: typeof import("../components/dark/home-main/Marquee.vue")['default']
export const DarkHomeMainPortfolio: typeof import("../components/dark/home-main/Portfolio.vue")['default']
export const DarkHomeMainServices: typeof import("../components/dark/home-main/Services.vue")['default']
export const DarkHomeMainServices2: typeof import("../components/dark/home-main/Services2.vue")['default']
export const DarkHomeMainTeam: typeof import("../components/dark/home-main/Team.vue")['default']
export const DarkHomeMainTestimonials: typeof import("../components/dark/home-main/Testimonials.vue")['default']
export const DarkInteractiveFullInteractive: typeof import("../components/dark/interactive-full/Interactive.vue")['default']
export const DarkPortfolioHeader: typeof import("../components/dark/portfolio/Header.vue")['default']
export const DarkPortfolioNavbar: typeof import("../components/dark/portfolio/Navbar.vue")['default']
export const DarkPortfolio: typeof import("../components/dark/portfolio/Portfolio.vue")['default']
export const DarkProjectChallenge: typeof import("../components/dark/project/Challenge.vue")['default']
export const DarkProjectHeader: typeof import("../components/dark/project/Header.vue")['default']
export const DarkProjectNext: typeof import("../components/dark/project/Next.vue")['default']
export const DarkProjectSolution: typeof import("../components/dark/project/Solution.vue")['default']
export const DarkProjectWorks: typeof import("../components/dark/project/Works.vue")['default']
export const DarkProjectWorks2: typeof import("../components/dark/project/Works2.vue")['default']
export const DarkServicesDetailsFAQS: typeof import("../components/dark/services-details/FAQS.vue")['default']
export const DarkServicesDetailsHeader: typeof import("../components/dark/services-details/Header.vue")['default']
export const DarkServicesDetailsProcess: typeof import("../components/dark/services-details/Process.vue")['default']
export const DarkServicesDetailsServices: typeof import("../components/dark/services-details/Services.vue")['default']
export const DarkServicesBlog: typeof import("../components/dark/services/Blog.vue")['default']
export const DarkServicesHeader: typeof import("../components/dark/services/Header.vue")['default']
export const DarkServicesMarquee: typeof import("../components/dark/services/Marquee.vue")['default']
export const DarkServicesPrice: typeof import("../components/dark/services/Price.vue")['default']
export const DarkServicesProcess: typeof import("../components/dark/services/Process.vue")['default']
export const DarkServices: typeof import("../components/dark/services/Services.vue")['default']
export const DarkServicesServices2: typeof import("../components/dark/services/Services2.vue")['default']
export const DarkServices2Brands: typeof import("../components/dark/services2/Brands.vue")['default']
export const DarkShowcaseFullscreenHeader: typeof import("../components/dark/showcase-fullscreen/Header.vue")['default']
export const DarkTeamHeader: typeof import("../components/dark/team/Header.vue")['default']
export const DarkTeam: typeof import("../components/dark/team/Team.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAbout: typeof import("../components/About.vue")['default']
export const LazyBlog: typeof import("../components/Blog.vue")['default']
export const LazyClients: typeof import("../components/Clients.vue")['default']
export const LazyContact: typeof import("../components/Contact.vue")['default']
export const LazyError: typeof import("../components/Error.vue")['default']
export const LazyFooter2: typeof import("../components/Footer2.vue")['default']
export const LazyFooterPrimary: typeof import("../components/FooterPrimary.vue")['default']
export const LazyFooterSecondary: typeof import("../components/FooterSecondary.vue")['default']
export const LazyFooterTertiary: typeof import("../components/FooterTertiary.vue")['default']
export const LazyHeroMain: typeof import("../components/HeroMain.vue")['default']
export const LazyImageScale: typeof import("../components/ImageScale.vue")['default']
export const LazyMarquee: typeof import("../components/Marquee.vue")['default']
export const LazyNavbar: typeof import("../components/Navbar.vue")['default']
export const LazyPortfolio: typeof import("../components/Portfolio.vue")['default']
export const LazyServices: typeof import("../components/Services.vue")['default']
export const LazySkills: typeof import("../components/Skills.vue")['default']
export const LazyTestimonials: typeof import("../components/Testimonials.vue")['default']
export const LazyCommonFooter: typeof import("../components/common/Footer.vue")['default']
export const LazyCommonLines: typeof import("../components/common/Lines.vue")['default']
export const LazyCommonProgressScroll: typeof import("../components/common/ProgressScroll.vue")['default']
export const LazyCommonCusor: typeof import("../components/common/cusor.vue")['default']
export const LazyCommonLoader: typeof import("../components/common/loader.vue")['default']
export const LazyDarkAbout: typeof import("../components/dark/About.vue")['default']
export const LazyDarkAboutBlog: typeof import("../components/dark/about/Blog.vue")['default']
export const LazyDarkAboutFooter: typeof import("../components/dark/about/Footer.vue")['default']
export const LazyDarkAboutHeader: typeof import("../components/dark/about/Header.vue")['default']
export const LazyDarkAboutIntro: typeof import("../components/dark/about/Intro.vue")['default']
export const LazyDarkAboutIntro2: typeof import("../components/dark/about/Intro2.vue")['default']
export const LazyDarkAboutMarquee: typeof import("../components/dark/about/Marquee.vue")['default']
export const LazyDarkAboutTeam: typeof import("../components/dark/about/Team.vue")['default']
export const LazyDarkAboutTestimonials: typeof import("../components/dark/about/Testimonials.vue")['default']
export const LazyDarkBlogClassicFooter: typeof import("../components/dark/blog-classic/Footer.vue")['default']
export const LazyDarkBlogDetailsBlog: typeof import("../components/dark/blog-details/Blog.vue")['default']
export const LazyDarkBlogDetailsFooter: typeof import("../components/dark/blog-details/Footer.vue")['default']
export const LazyDarkBlogDetailsRecent: typeof import("../components/dark/blog-details/Recent.vue")['default']
export const LazyDarkBlogDetailsSlider: typeof import("../components/dark/blog-details/Slider.vue")['default']
export const LazyDarkBlogListBlogs: typeof import("../components/dark/blog-list/Blogs.vue")['default']
export const LazyDarkBlogListHeader: typeof import("../components/dark/blog-list/Header.vue")['default']
export const LazyDarkContact: typeof import("../components/dark/contact/Contact.vue")['default']
export const LazyDarkContactHeader: typeof import("../components/dark/contact/Header.vue")['default']
export const LazyDarkCreativeAgencyFooter: typeof import("../components/dark/creative-agency/Footer.vue")['default']
export const LazyDarkCreativeAgencyNavbar: typeof import("../components/dark/creative-agency/Navbar.vue")['default']
export const LazyDarkFaqBlog: typeof import("../components/dark/faq/Blog.vue")['default']
export const LazyDarkFaqFAQS: typeof import("../components/dark/faq/FAQS.vue")['default']
export const LazyDarkFaqHeader: typeof import("../components/dark/faq/Header.vue")['default']
export const LazyDarkFaqTestimonials: typeof import("../components/dark/faq/Testimonials.vue")['default']
export const LazyDarkHomeMainBlog: typeof import("../components/dark/home-main/Blog.vue")['default']
export const LazyDarkHomeMainClients: typeof import("../components/dark/home-main/Clients.vue")['default']
export const LazyDarkHomeMainFooter: typeof import("../components/dark/home-main/Footer.vue")['default']
export const LazyDarkHomeMainHeader: typeof import("../components/dark/home-main/Header.vue")['default']
export const LazyDarkHomeMainIntro: typeof import("../components/dark/home-main/Intro.vue")['default']
export const LazyDarkHomeMainMarquee: typeof import("../components/dark/home-main/Marquee.vue")['default']
export const LazyDarkHomeMainPortfolio: typeof import("../components/dark/home-main/Portfolio.vue")['default']
export const LazyDarkHomeMainServices: typeof import("../components/dark/home-main/Services.vue")['default']
export const LazyDarkHomeMainServices2: typeof import("../components/dark/home-main/Services2.vue")['default']
export const LazyDarkHomeMainTeam: typeof import("../components/dark/home-main/Team.vue")['default']
export const LazyDarkHomeMainTestimonials: typeof import("../components/dark/home-main/Testimonials.vue")['default']
export const LazyDarkInteractiveFullInteractive: typeof import("../components/dark/interactive-full/Interactive.vue")['default']
export const LazyDarkPortfolioHeader: typeof import("../components/dark/portfolio/Header.vue")['default']
export const LazyDarkPortfolioNavbar: typeof import("../components/dark/portfolio/Navbar.vue")['default']
export const LazyDarkPortfolio: typeof import("../components/dark/portfolio/Portfolio.vue")['default']
export const LazyDarkProjectChallenge: typeof import("../components/dark/project/Challenge.vue")['default']
export const LazyDarkProjectHeader: typeof import("../components/dark/project/Header.vue")['default']
export const LazyDarkProjectNext: typeof import("../components/dark/project/Next.vue")['default']
export const LazyDarkProjectSolution: typeof import("../components/dark/project/Solution.vue")['default']
export const LazyDarkProjectWorks: typeof import("../components/dark/project/Works.vue")['default']
export const LazyDarkProjectWorks2: typeof import("../components/dark/project/Works2.vue")['default']
export const LazyDarkServicesDetailsFAQS: typeof import("../components/dark/services-details/FAQS.vue")['default']
export const LazyDarkServicesDetailsHeader: typeof import("../components/dark/services-details/Header.vue")['default']
export const LazyDarkServicesDetailsProcess: typeof import("../components/dark/services-details/Process.vue")['default']
export const LazyDarkServicesDetailsServices: typeof import("../components/dark/services-details/Services.vue")['default']
export const LazyDarkServicesBlog: typeof import("../components/dark/services/Blog.vue")['default']
export const LazyDarkServicesHeader: typeof import("../components/dark/services/Header.vue")['default']
export const LazyDarkServicesMarquee: typeof import("../components/dark/services/Marquee.vue")['default']
export const LazyDarkServicesPrice: typeof import("../components/dark/services/Price.vue")['default']
export const LazyDarkServicesProcess: typeof import("../components/dark/services/Process.vue")['default']
export const LazyDarkServices: typeof import("../components/dark/services/Services.vue")['default']
export const LazyDarkServicesServices2: typeof import("../components/dark/services/Services2.vue")['default']
export const LazyDarkServices2Brands: typeof import("../components/dark/services2/Brands.vue")['default']
export const LazyDarkShowcaseFullscreenHeader: typeof import("../components/dark/showcase-fullscreen/Header.vue")['default']
export const LazyDarkTeamHeader: typeof import("../components/dark/team/Header.vue")['default']
export const LazyDarkTeam: typeof import("../components/dark/team/Team.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
